---
- name: download node exporter
  unarchive:
    src: http://download.redis.io/releases/redis-5.0.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: compile
  command: make
  args:
    chdir: /tmp/redis-5.0.3

- name: move redis binary
  command: mv /tmp/redis-5.0.3 /usr/bin/

- name: create redis dir
  file: path=/etc/redis state=directory

- name: copy config file
  template:
    src: redis.conf.j2
    dest: "/etc/redis/redis.conf"

