---
- name: copy ssh keys
  copy:
    src: files/ssh_authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: 0600

- name: add gandi apt key
  apt_key:
    url: https://mirrors.gandi.net/gandi/pubkey
    id: D9A579D6BB859933
    state: present

- name: update and upgrade
  apt:
    update_cache: yes
    upgrade: dist
